### ISSUE TITLE
GUID_generator-demo test case fails when compiled with "-fsanitize=address -fsanitize=leak" sanitizers

### ISSUE THREAD

**Issue by TrinityCoder** [TrinityCoder/libut#1]
After today's commit, which brought sanitizers (AddressSanitizer and LeakSanitizer) into all test executables, everything works fine except one test case - _GUID_generator-demo-sanitizers_ always fails when executed.

This is program output:

```sh
mirek@home:~/github/libut/build$ ./GUID_generator-demo-sanitizers 
REQUIRE((libut::guid::get() == 1u))
REQUIRE((libut::guid::get() == 2u))
REQUIRE((libut::guid::get() == 3u))
REQUIRE((libut::guid::get() == 4u))
REQUIRE((libut::guid::get() == 5u))
[Multithread test] Launching multithread access test - 200 threads, each will call GUID generator 2000 times to obtain a GUID... (in total: 400000 unique GUID requests)
ASAN:DEADLYSIGNAL
=================================================================
==17984==ERROR: AddressSanitizer: SEGV on unknown address 0x607000000010 (pc 0x7f296718a085 bp 0x7ffca30c8230 sp 0x7ffca30c81e0 T0)
==17984==The signal is caused by a WRITE memory access.
    #0 0x7f296718a084  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x26084)
    #1 0x7f296723d663 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xd9663)
    #2 0x7f29652665d4  (/lib/x86_64-linux-gnu/libdl.so.2+0x15d4)
    #3 0x7f2965266067 in dlsym (/lib/x86_64-linux-gnu/libdl.so.2+0x1067)
    #4 0x7f29662df686  (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0x1e686)
    #5 0x7f29662ca169  (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0x9169)
    #6 0x7f29662ce9c4 in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xd9c4)
    #7 0x7f296719b1d5 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x371d5)
    #8 0x7f2965ddd9f4 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xba9f4)
    #9 0x404b06 in thread<(lambda at /home/mirek/github/libut/demo/GUID_generator.cpp:52:26) &> /usr/bin/../lib/gcc/x86_64-linux-gnu/7.1.0/../../../../include/c++/7.1.0/thread:126
    #10 0x4029f0 in main /home/mirek/github/libut/demo/GUID_generator.cpp:71
    #11 0x7f29654892b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #12 0x401c89 in _start (/home/mirek/github/libut/build/GUID_generator-demo-sanitizers+0x401c89)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x26084) 
==17984==ABORTING
mirek@home:~/github/libut/build
```

It seems that it has something to do with allocating those 200 threads. I will investigate and report back when I discover something interesting, hopefully ASAP.

**Comment by TrinityCoder** [comment]
Issue resolved in commit: 22eaf06112ed95a0127d8cc4eb1d3f081837ec7b

Explanation: It seems we can not use both AddressSanitizer and LeakSanitizer at the same time, so I have removed LeakSanitizer completely. Now everything works.
